//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Bill()
        {
            this.tbl_BillDetail = new HashSet<tbl_BillDetail>();
        }
    
        public int id { get; set; }
        public byte level_status { get; set; }
        public int cus_id { get; set; }
        public System.DateTime created_at { get; set; }
        public int total_price { get; set; }
        public string cus_name { get; set; }
        public string cus_address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BillDetail> tbl_BillDetail { get; set; }
        public virtual tbl_Customer tbl_Customer { get; set; }
    }
}
