//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Product()
        {
            this.tbl_BillDetail = new HashSet<tbl_BillDetail>();
            this.tbl_Cart = new HashSet<tbl_Cart>();
        }
    
        public int id { get; set; }
        public int cate_id { get; set; }
        public string name { get; set; }
        public string meta_name { get; set; }
        public string img { get; set; }
        public byte rate { get; set; }
        public int amount { get; set; }
        public int price { get; set; }
        public int discount { get; set; }
        public System.DateTime get_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BillDetail> tbl_BillDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Cart> tbl_Cart { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
